spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

logging:
  level:
    root: debug
    org:
      springframework:
        security: DEBUG
server:
  servlet:
    context-path: /api/v1